apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T13:51:01Z"
  name: carts-canary
  resourceVersion: "956825"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 82939de4-6468-11ea-8199-42010a840049
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
